name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - staging
          - production
        default: staging
      skip-tests:
        description: 'Skip tests (use with caution)'
        required: false
        type: boolean
        default: false

env:
  PHP_VERSION: '8.3'
  NODE_VERSION: '20'

permissions:
  contents: read
  deployments: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}-${{ inputs.environment || 'production' }}
  cancel-in-progress: false

jobs:
  pre-deployment-checks:
    name: Pre-deployment Validation
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      deploy-version: ${{ steps.version.outputs.version }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Determine Version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="main-$(git rev-parse --short HEAD)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Deploying version: $VERSION"
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, dom, fileinfo, mysql, redis, opcache
          tools: composer:v2
          coverage: none
          
      - name: Validate Composer Files
        run: composer validate --strict
        
      - name: Check for Security Vulnerabilities
        run: |
          composer audit --no-dev || AUDIT_FAILED=1
          if [ "$AUDIT_FAILED" == "1" ]; then
            echo "::warning::Security vulnerabilities found in dependencies"
          fi
          
      - name: Run Critical Tests
        if: ${{ !inputs.skip-tests }}
        run: |
          composer install --prefer-dist --no-progress --optimize-autoloader
          ./vendor/bin/pest tests/Unit --stop-on-failure

  build-artifacts:
    name: Build Release Artifacts
    needs: [pre-deployment-checks]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, dom, fileinfo, mysql, redis, opcache
          tools: composer:v2
          coverage: none
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install PHP Dependencies (Production)
        run: |
          composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
          composer dump-autoload --optimize --no-dev
          
      - name: Install Node Dependencies
        run: npm ci --prefer-offline --no-audit
        
      - name: Build Frontend Assets
        run: |
          npm run build
          rm -rf node_modules
          
      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan event:cache
          
      - name: Create Deployment Package
        run: |
          tar -czf deploy-${{ needs.pre-deployment-checks.outputs.deploy-version }}.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='tests' \
            --exclude='*.test.js' \
            --exclude='*.spec.js' \
            --exclude='.env*' \
            --exclude='storage/app/*' \
            --exclude='storage/logs/*' \
            --exclude='storage/framework/cache/*' \
            --exclude='storage/framework/sessions/*' \
            --exclude='storage/framework/views/*' \
            .
            
      - name: Upload Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package-${{ needs.pre-deployment-checks.outputs.deploy-version }}
          path: deploy-*.tar.gz
          retention-days: 7

  deploy-staging:
    name: Deploy to Staging
    needs: [pre-deployment-checks, build-artifacts]
    if: github.event.inputs.environment == 'staging' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 30
    
    steps:
      - name: Download Deployment Package
        uses: actions/download-artifact@v4
        with:
          name: deployment-package-${{ needs.pre-deployment-checks.outputs.deploy-version }}
          
      - name: Deploy to Staging Environment
        run: |
          echo "::notice::Deploying version ${{ needs.pre-deployment-checks.outputs.deploy-version }} to staging"
          # In a real scenario, this would:
          # 1. Connect to staging server via SSH
          # 2. Backup current deployment
          # 3. Extract deployment package
          # 4. Run database migrations
          # 5. Clear caches
          # 6. Restart services
          # 7. Run smoke tests
          
      - name: Run Post-deployment Tests
        run: |
          echo "Running smoke tests on staging..."
          # curl https://staging.example.com/health
          # Run E2E tests against staging
          
      - name: Notify Deployment Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Successfully deployed to staging"
          else
            echo "❌ Staging deployment failed"
          fi

  deploy-production:
    name: Deploy to Production
    needs: [pre-deployment-checks, build-artifacts, deploy-staging]
    if: |
      (github.event.inputs.environment == 'production' && github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 45
    
    steps:
      - name: Download Deployment Package
        uses: actions/download-artifact@v4
        with:
          name: deployment-package-${{ needs.pre-deployment-checks.outputs.deploy-version }}
          
      - name: Create Deployment Record
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              task: 'deploy',
              auto_merge: false,
              required_contexts: [],
              environment: 'production',
              description: 'Production deployment v${{ needs.pre-deployment-checks.outputs.deploy-version }}'
            });
            
            core.setOutput('deployment_id', deployment.data.id);
            
      - name: Deploy to Production
        id: deploy
        run: |
          echo "::notice::Deploying version ${{ needs.pre-deployment-checks.outputs.deploy-version }} to production"
          
          # Production deployment steps:
          # 1. Enable maintenance mode
          # 2. Backup database and files
          # 3. Deploy new code
          # 4. Run migrations with backup
          # 5. Clear all caches
          # 6. Warm up caches
          # 7. Disable maintenance mode
          # 8. Verify deployment
          
          echo "deploy_status=success" >> $GITHUB_OUTPUT
          
      - name: Update Deployment Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.deploy.outputs.deployment_id }},
              state: '${{ steps.deploy.outputs.deploy_status || 'failure' }}',
              log_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Production deployment ${{ steps.deploy.outputs.deploy_status || 'failed' }}',
              environment: 'production'
            });
            
      - name: Run Production Smoke Tests
        if: success()
        run: |
          echo "Running production smoke tests..."
          # Verify critical endpoints
          # Check database connectivity
          # Verify queue workers
          # Test payment processing (in test mode)
          
      - name: Rollback on Failure
        if: failure()
        run: |
          echo "::error::Production deployment failed! Initiating rollback..."
          # Rollback steps would go here

  post-deployment:
    name: Post-deployment Tasks
    needs: [pre-deployment-checks, deploy-production]
    if: success()
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Clear CDN Cache
        run: |
          echo "Clearing CDN cache..."
          # Clear Cloudflare/CDN cache
          
      - name: Update Monitoring
        run: |
          echo "Updating monitoring dashboards..."
          # Update DataDog/New Relic with deployment marker
          
      - name: Notify Team
        run: |
          echo "Deployment completed successfully!"
          echo "Version: ${{ needs.pre-deployment-checks.outputs.deploy-version }}"
          # Send Slack/Discord notification
          
      - name: Create Release Notes
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: `Release ${tag}`,
              body: `## What's Changed\n\nFull changelog: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/compare/...${tag}`,
              draft: false,
              prerelease: false
            });