name: Security

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        id: gitleaks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          # Use the .gitleaks.toml config file
          config_path: .gitleaks.toml
          
      # Report the result but don't fail the workflow
      - name: Report Gitleaks Status
        if: always()
        run: |
          if [ "${{ steps.gitleaks.outcome }}" == "failure" ]; then
            echo "::warning::Gitleaks detected potential secrets. Please review the findings."
            echo "This is currently non-blocking due to false positives in documentation."
          else
            echo "✅ No secrets detected by Gitleaks"
          fi